name: fuzzer-test-mxnet
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7.6
  - pip:
    - mxnet==1.6.0
    - ruamel-yaml==0.16.10
    - scikit-learn==0.22.2.post1
    - networkx==2.4
