name: fuzzer-test
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7.6
  - pip:
    - ruamel-yaml==0.16.10
    - tensorflow==2.1.0
    - scikit-learn==0.22.2.post1
    - networkx==2.4
