aliases:
- tf.compat.v1.config.threading.set_intra_op_parallelism_threads
constraints:
  num_threads:
    descp: Number of parallel threads
    ndim:
    - '0'
    range:
    - '[0,inf)'
inputs:
  optional: []
  required:
  - num_threads
link: https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/config/threading/set_intra_op_parallelism_threads
package: tensorflow
target: set_intra_op_parallelism_threads
title: tf.config.threading.set_intra_op_parallelism_threads
version: 2.1.0
